version: 2.0
jobs:
  gns:
    docker:
      - image: quay.io/geoelements/gns
    steps:
      - checkout
      # GCC
      - run:
          name: Train & Test
          command: |
            TMP_DIR="./gns-sample"
            DATASET_NAME="WaterDropSample"
            git clone https://github.com/geoelements/gns-sample.git 
            DATA_PATH="${TMP_DIR}/${DATASET_NAME}/datasets/"
            MODEL_PATH="${TMP_DIR}/${DATASET_NAME}/models/"
            python -m gns.train --data_path=${DATA_PATH} --model_path=${MODEL_PATH} --ntraining_steps=10 --mode='train'

workflows:
    version: 2
    build:
        jobs:
            - gns