version: 2.1

workflows:
  build:
    jobs:
      - python37

jobs:
  python37: &test-template
    docker:
      - image: cimg/python:3.7.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            virtualenv venv
            . venv/bin/activate
      - run:
          name: Install gns dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover test/
