version: 2.0
jobs:
  gns:
    docker:
      - image: quay.io/geoelements/gns
    steps:
      - checkout
      # GCC
      - run:
          name: Train & Test
          command: |
            TMP_DIR="./gns-sample-main"
            DATASET_NAME="WaterDropSample"
            mkdir -p ${TMP_DIR}/models/${DATASET_NAME}
            wget https://github.com/geoelements/gns-sample/archive/refs/heads/main.zip && unzip main.zip
            DATA_PATH="${TMP_DIR}/datasets/${DATASET_NAME}"
            MODEL_PATH="${TMP_DIR}/models/${DATASET_NAME}"
            python -m gns.train --data_path=${DATA_PATH} --model_path=${MODEL_PATH} --ntraining_steps=10 --mode='train'

workflows:
    version: 2
    build:
        jobs:
            - gns